name: Industrialisation continue sur le serveur Alwaysdata

on:
  push

jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur (clé privée)
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd $HOME/www/
            echo "✅ Connexion SSH réussie"
  
  Copy:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du dépôt GitHub
        uses: actions/checkout@v3

      - name: Connexion SSH et copie du projet
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd $HOME/www/
            repo_name=$(basename ${{ github.repository }})
            rm -rf $repo_name
            git clone https://github.com/${{ github.repository }}.git
            echo "✅ Projet cloné"

  Restart:
    needs: Copy
    runs-on: ubuntu-latest
    steps:
      - name: Restart Alwaysdata site
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST --basic --user "${{ secrets.ALWAYSDATA_TOKEN }}:" https://api.alwaysdata.com/v1/site/${{ secrets.ALWAYSDATA_SITE_ID }}/restart/)
          if [ "$response_code" -eq 204 ]; then
            echo "✅ Site redémarré avec succès"
          elif [ "$response_code" -eq 404 ]; then
            echo "❌ ALWAYSDATA_SITE_ID incorrect"
            exit 1
          elif [ "$response_code" -eq 401 ]; then
            echo "❌ ALWAYSDATA_TOKEN incorrect"
            exit 1
          else
            echo "❌ Erreur inconnue ($response_code)"
            exit 1
          fi
